# Generated by Django 4.2.7 on 2025-08-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_firebase_uid_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
