# Generated by Django 4.2.7 on 2025-08-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_firebase_uid_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_access',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jwt_refresh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
