# Generated by Django 4.2.7 on 2025-08-16 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('user_audio', models.FileField(blank=True, null=True, upload_to='speaking/user_audio/')),
                ('user_text', models.TextField(blank=True, null=True)),
                ('ai_text', models.TextField(blank=True, null=True)),
                ('ai_audio', models.FileField(blank=True, null=True, upload_to='speaking/ai_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
